### ISSUE TITLE
Course Module

### ISSUE THREAD

**Issue by Ajmal112** [fssa-batch3/sec_a_mohammedajmal.iqbol__corejava_project_2#14]
### Description:
Develop the backend functionalities for course management.

### Tasks:
- [ ] #5 
- [ ] #6 
- [ ] #7 
- [ ] #8 

### Attributes:

- [ ] Course Id
- [ ] Cover Image
- [ ] Name
- [ ] Timing
- [ ] Language
- [ ] Marked Price
- [ ] Selling Price
- [ ] Description
- [ ] Instructor Name
- [ ] Company Name
- [ ] Company Category
- [ ] Top Skills

### Validation:
- [ ] Validate Image URL
- [ ]  Validate Name
- [ ] Validate Language
- [ ]  Validate Marked Price
- [ ] Validate Selling Price
- [ ] Validate Price Difference
- [ ] Validate Timing
- [ ] Validate Instructor Name
- [ ] Validate Company Name
- [ ] Validate Comp Category
- [ ] Validate Top Skills

### Validation Tests:
- [ ] testValidateUser()
- [ ] testValidateName()
- [ ] testValidatePassword()
- [ ] testValidateEmail()
