### ISSUE TITLE
Course Purchase Module | Course Completion Feature

### ISSUE THREAD

**Issue by Ajmal112** [fssa-batch3/sec_a_mohammedajmal.iqbol__corejava_project_2#19]
# User Course Completion Process

### User Story

- Users can get course completion certificate after he completed the full course 100% 
- else he can't get course completion certificate.

### Task

- [ ] Implement Data Access Object (DAO) Layer.
- [ ] Implement Service Layer.
- [ ] Write clear and concise comments in the code to explain complex logic.

### DAO:
- courseCompletion()

### Service:
- courseComplete()

### Estimation
- 2:30 hours
