### ISSUE TITLE
Daily Quiz Feature

### ISSUE THREAD

**Issue by Ajmal112** [fssa-batch3/sec_a_mohammedajmal.iqbol__corejava_project_2#20]
# User Daily Quiz feature

### User Story

- Users can get a streak when he answer the correct answer
- else he can't get streak, the streak will decrease by one.
- this quiz is answered once a day.

### Task

- [ ] Implement Data Access Object (DAO) Layer.
- [ ] Implement Service Layer.
- [ ] Write clear and concise comments in the code to explain complex logic.

### DAO:
- insertOrUpdateQuizData

### Service:
- insertOrUpdateUserQuizData()

### Estimation
- 3:30 hours
