### ISSUE TITLE
Course Module | Create Feature

### ISSUE THREAD

**Issue by Ajmal112** [fssa-batch3/sec_a_mohammedajmal.iqbol__corejava_project_2#5]
# Course Create Process

### User Story 

- When an instructor/administrator provides valid input while creating a new course, the system accurately captures all the required information, successfully adds the course to the system, and provides confirmation of the successful creation.
- When an instructor/administrator provides Invalid input while attempting to create a new course, the system detects the errors and provides appropriate error messages to guide them in correcting the input

### Task

- [x] Implement Data Access Object (DAO) Layer.
- [x] Implement Service Layer.
- [x] Create JUnit Test Cases.
- [x] Ensure that the test cases are passing.
- [x] Write clear and concise comments in the code to explain complex logic.

### DAO
- createCourse()

### Service
- registerCourse()

### Service Test
TestCreateCourseFeature
- testCreateCourseSuccess()
- testCreateCourseFailure()

### Estimation
- 1 hour

# Flowchart

```mermaid
flowchart TD
A[Start]
B[User Requests to Create Course]
C[Display Course Creation Form]
D[User Provides Course Details]
E[Validate Input]
F{Validation Successful?}
G[Save Course Data]
H[Course Creation Successful]
I[Display Error Messages]
J[End]

A --> B
B --> C
C --> D
D --> E
E --> F
F -- Yes --> G
G --> H
F -- No --> I
I --> C
I --> J
H --> J
```

**Comment by Ajmal112** [comment]
done

**Comment by Vinit-source** [comment]
- [x] - listCourse can have userID.
- [x] - Error messages should be more helpful
- [x] - Make sure all test cases pass.

**Comment by Vinit-source** [comment]
- [ ] revise the SQL script. Add insert query and also make the script such that it is create a ready to demo DB for milestone 2.
- [ ] Reduce SonarCloud code smells to less than 10 and avoid duplications.
- [ ] Complete JavaDocs.
